import 'package:dart_application_1/TryCatchFinallyWithCustomException.dart';

void main() {
  accessArraySafeWithCustomException(1);
  accessArraySafeWithCustomException(5);
}